var group__DataBoxTagsGroup =
[
    [ "control_system::measurements::Tags::NeutronStarCenter< Center >", "structcontrol__system_1_1measurements_1_1Tags_1_1NeutronStarCenter.html", null ],
    [ "control_system::Tags::IsActive< ControlSystem >", "structcontrol__system_1_1Tags_1_1IsActive.html", null ],
    [ "control_system::Tags::MeasurementTimescales", "structcontrol__system_1_1Tags_1_1MeasurementTimescales.html", null ],
    [ "control_system::Tags::WriteDataToDisk", "structcontrol__system_1_1Tags_1_1WriteDataToDisk.html", null ],
    [ "control_system::Tags::ObserveCenters", "structcontrol__system_1_1Tags_1_1ObserveCenters.html", null ],
    [ "control_system::Tags::Averager< ControlSystem >", "structcontrol__system_1_1Tags_1_1Averager.html", null ],
    [ "control_system::Tags::TimescaleTuner< ControlSystem >", "structcontrol__system_1_1Tags_1_1TimescaleTuner.html", null ],
    [ "control_system::Tags::Controller< ControlSystem >", "structcontrol__system_1_1Tags_1_1Controller.html", null ],
    [ "control_system::Tags::ControlError< ControlSystem >", "structcontrol__system_1_1Tags_1_1ControlError.html", null ],
    [ "control_system::Tags::MeasurementsPerUpdate", "structcontrol__system_1_1Tags_1_1MeasurementsPerUpdate.html", null ],
    [ "control_system::Tags::CurrentNumberOfMeasurements", "structcontrol__system_1_1Tags_1_1CurrentNumberOfMeasurements.html", null ],
    [ "control_system::Tags::Verbosity", "structcontrol__system_1_1Tags_1_1Verbosity.html", null ],
    [ "Tags::DataBox", "structTags_1_1DataBox.html", null ],
    [ "Tags::dt< Tag >", "structTags_1_1dt.html", null ],
    [ "Tags::Flux< Tag, VolumeDim, Fr, typename >", "structTags_1_1Flux.html", null ],
    [ "Tags::Source< Tag >", "structTags_1_1Source.html", null ],
    [ "Tags::FixedSource< Tag >", "structTags_1_1FixedSource.html", null ],
    [ "Tags::Initial< Tag >", "structTags_1_1Initial.html", null ],
    [ "Tags::NormalDotFlux< Tag >", "structTags_1_1NormalDotFlux.html", null ],
    [ "Tags::NormalDotNumericalFlux< Tag >", "structTags_1_1NormalDotNumericalFlux.html", null ],
    [ "Tags::Next< Tag >", "structTags_1_1Next.html", null ],
    [ "Tags::Magnitude< Tag >", "structTags_1_1Magnitude.html", null ],
    [ "Tags::EuclideanMagnitude< Tag >", "structTags_1_1EuclideanMagnitude.html", null ],
    [ "Tags::NonEuclideanMagnitude< Tag, MetricTag >", "structTags_1_1NonEuclideanMagnitude.html", null ],
    [ "Tags::Normalized< Tag >", "structTags_1_1Normalized.html", null ],
    [ "Tags::NormalizedCompute< Tag >", "structTags_1_1NormalizedCompute.html", null ],
    [ "Tags::PointwiseL2Norm< Tag >", "structTags_1_1PointwiseL2Norm.html", null ],
    [ "Tags::PointwiseL2NormCompute< Tag >", "structTags_1_1PointwiseL2NormCompute.html", null ],
    [ "Tags::L2Norm< Tag >", "structTags_1_1L2Norm.html", null ],
    [ "Tags::L2NormCompute< Tag >", "structTags_1_1L2NormCompute.html", null ],
    [ "domain::CoordinateMaps::Tags::CoordinateMap< VolumeDim, SourceFrame, TargetFrame >", "structdomain_1_1CoordinateMaps_1_1Tags_1_1CoordinateMap.html", null ],
    [ "domain::Tags::Domain< VolumeDim >", "structdomain_1_1Tags_1_1Domain.html", null ],
    [ "domain::Tags::InitialExtents< Dim >", "structdomain_1_1Tags_1_1InitialExtents.html", null ],
    [ "domain::Tags::InitialRefinementLevels< Dim >", "structdomain_1_1Tags_1_1InitialRefinementLevels.html", null ],
    [ "domain::Tags::ObjectCenter< Label >", "structdomain_1_1Tags_1_1ObjectCenter.html", null ],
    [ "domain::Tags::ExcisionCenter< Label >", "structdomain_1_1Tags_1_1ExcisionCenter.html", null ],
    [ "domain::Tags::UnnormalizedFaceNormal< VolumeDim, Frame >", "structdomain_1_1Tags_1_1UnnormalizedFaceNormal.html", null ],
    [ "domain::Tags::InterfaceCompute< Tags::BoundaryDirectionsExterior< VolumeDim >, UnnormalizedFaceNormalCompute< VolumeDim, Frame > >", "structdomain_1_1Tags_1_1InterfaceCompute_3_01Tags_1_1BoundaryDirectionsExterior_3_01VolumeDim_0184ce0938d30efe351cc7c3751f2e8f00.html", null ],
    [ "domain::Tags::InterfaceCompute< DirectionsTag, Tag >", "structdomain_1_1Tags_1_1InterfaceCompute.html", null ],
    [ "domain::Tags::Slice< DirectionsTag, Tag >", "structdomain_1_1Tags_1_1Slice.html", null ],
    [ "domain::Tags::InterfaceMesh< VolumeDim >", "structdomain_1_1Tags_1_1InterfaceMesh.html", null ],
    [ "domain::Tags::BoundaryCoordinates< VolumeDim, MovingMesh >", "structdomain_1_1Tags_1_1BoundaryCoordinates.html", null ],
    [ "domain::Tags::JacobianDiagnostic< Dim >", "structdomain_1_1Tags_1_1JacobianDiagnostic.html", null ],
    [ "domain::Tags::JacobianDiagnosticCompute< Dim, TargetFrame >", "structdomain_1_1Tags_1_1JacobianDiagnosticCompute.html", null ],
    [ "domain::Tags::MinimumGridSpacing< Dim, Frame >", "structdomain_1_1Tags_1_1MinimumGridSpacing.html", null ],
    [ "domain::Tags::SizeOfElement< VolumeDim >", "structdomain_1_1Tags_1_1SizeOfElement.html", null ],
    [ "domain::Tags::Element< VolumeDim >", "structdomain_1_1Tags_1_1Element.html", null ],
    [ "domain::Tags::Mesh< VolumeDim >", "structdomain_1_1Tags_1_1Mesh.html", null ],
    [ "domain::Tags::ElementMap< VolumeDim, TargetFrame >", "structdomain_1_1Tags_1_1ElementMap.html", null ],
    [ "domain::Tags::Coordinates< Dim, Frame >", "structdomain_1_1Tags_1_1Coordinates.html", null ],
    [ "domain::Tags::MappedCoordinates< MapTag, SourceCoordsTag, CoordinatesTag >", "structdomain_1_1Tags_1_1MappedCoordinates.html", null ],
    [ "domain::Tags::InverseJacobian< Dim, SourceFrame, TargetFrame >", "structdomain_1_1Tags_1_1InverseJacobian.html", null ],
    [ "domain::Tags::InverseJacobianCompute< MapTag, SourceCoordsTag >", "structdomain_1_1Tags_1_1InverseJacobianCompute.html", null ],
    [ "domain::Tags::Jacobian< Dim, SourceFrame, TargetFrame >", "structdomain_1_1Tags_1_1Jacobian.html", null ],
    [ "domain::Tags::JacobianCompute< Dim, SourceFrame, TargetFrame >", "structdomain_1_1Tags_1_1JacobianCompute.html", null ],
    [ "domain::Tags::DetInvJacobian< SourceFrame, TargetFrame >", "structdomain_1_1Tags_1_1DetInvJacobian.html", null ],
    [ "domain::Tags::DetInvJacobianCompute< Dim, SourceFrame, TargetFrame >", "structdomain_1_1Tags_1_1DetInvJacobianCompute.html", null ],
    [ "domain::Tags::VariablesBoundaryData", "structdomain_1_1Tags_1_1VariablesBoundaryData.html", null ],
    [ "domain::Tags::InternalDirections< VolumeDim >", "structdomain_1_1Tags_1_1InternalDirections.html", null ],
    [ "domain::Tags::BoundaryDirectionsInterior< VolumeDim >", "structdomain_1_1Tags_1_1BoundaryDirectionsInterior.html", null ],
    [ "domain::Tags::BoundaryDirectionsExterior< VolumeDim >", "structdomain_1_1Tags_1_1BoundaryDirectionsExterior.html", null ],
    [ "domain::Tags::Interface< DirectionsTag, Tag >", "structdomain_1_1Tags_1_1Interface.html", null ],
    [ "domain::Tags::Direction< VolumeDim >", "structdomain_1_1Tags_1_1Direction.html", null ],
    [ "Tags::NormalDotFluxCompute< Tag, VolumeDim, Fr >", "structTags_1_1NormalDotFluxCompute.html", null ],
    [ "Tags::Mortars< Tag, VolumeDim >", "structTags_1_1Mortars.html", null ],
    [ "Tags::MortarSize< Dim >", "structTags_1_1MortarSize.html", null ],
    [ "Tags::div< Tag, typename >", "structTags_1_1div.html", null ],
    [ "Tags::DivVariablesCompute< Tag, InverseJacobianTag >", "structTags_1_1DivVariablesCompute.html", null ],
    [ "Tags::DivVectorCompute< Tag, InverseJacobianTag >", "structTags_1_1DivVectorCompute.html", null ],
    [ "Tags::deriv< Tag, Dim, Frame, typename >", "structTags_1_1deriv.html", null ],
    [ "Tags::spacetime_deriv< Tag, Dim, Frame, typename >", "structTags_1_1spacetime__deriv.html", null ],
    [ "Tags::DerivCompute< VariablesTag, InverseJacobianTag, DerivTags >", "structTags_1_1DerivCompute.html", null ],
    [ "Tags::DerivTensorCompute< TensorTag, InverseJacobianTag >", "structTags_1_1DerivTensorCompute.html", null ],
    [ "domain::Tags::LogicalCoordinates< VolumeDim >", "structdomain_1_1Tags_1_1LogicalCoordinates.html", null ],
    [ "Parallel::Tags::GlobalCache", "structParallel_1_1Tags_1_1GlobalCache.html", null ],
    [ "Parallel::Tags::FromGlobalCache< CacheTag >", "structParallel_1_1Tags_1_1FromGlobalCache.html", null ],
    [ "Parallel::Tags::ArrayIndex", "structParallel_1_1Tags_1_1ArrayIndex.html", null ],
    [ "Parallel::Tags::InputSource", "structParallel_1_1Tags_1_1InputSource.html", null ],
    [ "Parallel::Tags::Metavariables", "structParallel_1_1Tags_1_1Metavariables.html", null ],
    [ "Tags::Analytic< Tag >", "structTags_1_1Analytic.html", null ],
    [ "Tags::TimeStepId", "structTags_1_1TimeStepId.html", null ],
    [ "Tags::TimeStep", "structTags_1_1TimeStep.html", null ],
    [ "Tags::Time", "structTags_1_1Time.html", null ],
    [ "Tags::HistoryEvolvedVariables< Tag >", "structTags_1_1HistoryEvolvedVariables.html", null ],
    [ "Tags::StepperError< Tag >", "structTags_1_1StepperError.html", null ],
    [ "Tags::PreviousStepperError< Tag >", "structTags_1_1PreviousStepperError.html", null ],
    [ "Tags::BoundaryHistory< LocalVars, RemoteVars, CouplingResult >", "structTags_1_1BoundaryHistory.html", null ],
    [ "Tags::TimeStepper< StepperType >", "structTags_1_1TimeStepper.html", null ],
    [ "Tags::StepChoosers", "structTags_1_1StepChoosers.html", null ],
    [ "db::add_tag_prefix", "group__DataBoxTagsGroup.html#gafeeced2a7fb41fdced8c55e76343f63c", null ],
    [ "db::prefix_variables", "group__DataBoxTagsGroup.html#gaf33705b3b63c4ec285a9e7efaf3a49b5", null ],
    [ "db::remove_all_prefixes", "group__DataBoxTagsGroup.html#ga871c7fbc846eed01d84bd1c00bda6a9e", null ],
    [ "db::remove_tag_prefix", "group__DataBoxTagsGroup.html#gae0f7c7c20a2a4908eebcb234302b1b4f", null ],
    [ "db::unprefix_variables", "group__DataBoxTagsGroup.html#ga6c218ff8fb5379660e5b86eacad2cd5b", null ],
    [ "db::wrap_tags_in", "group__DataBoxTagsGroup.html#ga3dda5a16c7f6baccd115de2c8f12394e", null ]
];