var group__ControlSystemGroup =
[
    [ "control_system", "namespacecontrol__system.html", null ],
    [ "control_system::Actions", "namespacecontrol__system_1_1Actions.html", null ],
    [ "control_system::ControlErrors", "namespacecontrol__system_1_1ControlErrors.html", null ],
    [ "control_system::Systems", "namespacecontrol__system_1_1Systems.html", null ],
    [ "control_system::size", "namespacecontrol__system_1_1size.html", null ],
    [ "control_system::protocols", "namespacecontrol__system_1_1protocols.html", null ],
    [ "control_system::OptionTags", "namespacecontrol__system_1_1OptionTags.html", null ],
    [ "control_system::QueueTags", "namespacecontrol__system_1_1QueueTags.html", null ],
    [ "control_system::Tags", "namespacecontrol__system_1_1Tags.html", null ],
    [ "control_system::metafunctions", "namespacecontrol__system_1_1metafunctions.html", null ],
    [ "control_system::Actions::Initialize< Metavariables, ControlSystem >", "structcontrol__system_1_1Actions_1_1Initialize.html", null ],
    [ "Averager< DerivOrder >", "classAverager.html", [
      [ "Average0thDeriv", "structAverager_1_1Average0thDeriv.html", null ],
      [ "AverageTimescaleFraction", "structAverager_1_1AverageTimescaleFraction.html", null ],
      [ "Averager", "classAverager.html#a2821e8d09e41ac6a29c3b1b8959f7f1e", null ],
      [ "assign_time_between_measurements", "classAverager.html#ad3d8b99c27e119b044547b533bddaa0c", null ],
      [ "average_time", "classAverager.html#a1a88800536ae21106e971fd8ed2a0ad5", null ],
      [ "avg_timescale_frac", "classAverager.html#a2980b6e387093a97b55577b73aab4d66", null ],
      [ "clear", "classAverager.html#a55f421053d7cde318bdf3ee43f8287d5", null ],
      [ "is_ready", "classAverager.html#a2390c7e2665965d9a67ea80c42d3bb8a", null ],
      [ "last_time_updated", "classAverager.html#a7818ef5c58f10c998520e9ce3d0e364e", null ],
      [ "operator()", "classAverager.html#a351ad95990b31b2e1c18890e63fd2519", null ],
      [ "update", "classAverager.html#a2a1321e284480a81329f9e1e2eead739", null ],
      [ "using_average_0th_deriv_of_q", "classAverager.html#afb7edc77f6e9aececb2cf09daa66dcf6", null ]
    ] ],
    [ "ControlComponent< Metavariables, ControlSystem >", "structControlComponent.html", null ],
    [ "Controller< DerivOrder >", "classController.html", [
      [ "UpdateFraction", "structController_1_1UpdateFraction.html", null ],
      [ "assign_time_between_updates", "classController.html#aa133d5cca01991325afd44cf3a179971", null ],
      [ "get_update_fraction", "classController.html#a84a47daae95082551d0e8a216ffecefa", null ],
      [ "is_ready", "classController.html#a51eed849fb0f1e73f611ba28467e332d", null ],
      [ "next_expiration_time", "classController.html#a92223c054e642a1fe108006e6e3fa0b9", null ],
      [ "set_initial_update_time", "classController.html#a2440ed37220189b7103f81e9def224c5", null ]
    ] ],
    [ "control_system::Event< ControlSystems >", "classcontrol__system_1_1Event.html", [
      [ "needs_evolved_variables", "classcontrol__system_1_1Event.html#a252bbc35f58d62b1a476209089bea917", null ]
    ] ],
    [ "control_system::measurements::Tags::NeutronStarCenter< Center >", "structcontrol__system_1_1measurements_1_1Tags_1_1NeutronStarCenter.html", null ],
    [ "control_system::RunCallbacks< Submeasurement, ControlSystems >", "structcontrol__system_1_1RunCallbacks.html", null ],
    [ "control_system::Tags::FunctionsOfTimeInitialize", "structcontrol__system_1_1Tags_1_1FunctionsOfTimeInitialize.html", null ],
    [ "control_system::Tags::IsActive< ControlSystem >", "structcontrol__system_1_1Tags_1_1IsActive.html", null ],
    [ "control_system::Tags::MeasurementTimescales", "structcontrol__system_1_1Tags_1_1MeasurementTimescales.html", null ],
    [ "control_system::OptionHolder< ControlSystem >", "structcontrol__system_1_1OptionHolder.html", [
      [ "Averager", "structcontrol__system_1_1OptionHolder_1_1Averager.html", null ],
      [ "ControlError", "structcontrol__system_1_1OptionHolder_1_1ControlError.html", null ],
      [ "Controller", "structcontrol__system_1_1OptionHolder_1_1Controller.html", null ],
      [ "IsActive", "structcontrol__system_1_1OptionHolder_1_1IsActive.html", null ],
      [ "TimescaleTuner", "structcontrol__system_1_1OptionHolder_1_1TimescaleTuner.html", null ]
    ] ],
    [ "control_system::OptionTags::ControlSystemGroup", "structcontrol__system_1_1OptionTags_1_1ControlSystemGroup.html", null ],
    [ "control_system::OptionTags::ControlSystemInputs< ControlSystem >", "structcontrol__system_1_1OptionTags_1_1ControlSystemInputs.html", null ],
    [ "control_system::OptionTags::WriteDataToDisk", "structcontrol__system_1_1OptionTags_1_1WriteDataToDisk.html", null ],
    [ "control_system::OptionTags::MeasurementsPerUpdate", "structcontrol__system_1_1OptionTags_1_1MeasurementsPerUpdate.html", null ],
    [ "control_system::OptionTags::Verbosity", "structcontrol__system_1_1OptionTags_1_1Verbosity.html", null ],
    [ "control_system::QueueTags::Center< Horizon >", "structcontrol__system_1_1QueueTags_1_1Center.html", null ],
    [ "control_system::QueueTags::Horizon< Frame >", "structcontrol__system_1_1QueueTags_1_1Horizon.html", null ],
    [ "control_system::QueueTags::ExcisionSurface< Frame >", "structcontrol__system_1_1QueueTags_1_1ExcisionSurface.html", null ],
    [ "control_system::QueueTags::LapseOnExcisionSurface", "structcontrol__system_1_1QueueTags_1_1LapseOnExcisionSurface.html", null ],
    [ "control_system::QueueTags::ShiftyQuantity< Frame >", "structcontrol__system_1_1QueueTags_1_1ShiftyQuantity.html", null ],
    [ "control_system::QueueTags::SpatialMetricOnExcisionSurface< Frame >", "structcontrol__system_1_1QueueTags_1_1SpatialMetricOnExcisionSurface.html", null ],
    [ "control_system::QueueTags::InverseSpatialMetricOnExcisionSurface< Frame >", "structcontrol__system_1_1QueueTags_1_1InverseSpatialMetricOnExcisionSurface.html", null ],
    [ "control_system::QueueTags::SizeExcisionQuantities< Frame >", "structcontrol__system_1_1QueueTags_1_1SizeExcisionQuantities.html", null ],
    [ "control_system::QueueTags::SizeHorizonQuantities< Frame >", "structcontrol__system_1_1QueueTags_1_1SizeHorizonQuantities.html", null ],
    [ "control_system::Tags::WriteDataToDisk", "structcontrol__system_1_1Tags_1_1WriteDataToDisk.html", null ],
    [ "control_system::Tags::ObserveCenters", "structcontrol__system_1_1Tags_1_1ObserveCenters.html", null ],
    [ "control_system::Tags::Averager< ControlSystem >", "structcontrol__system_1_1Tags_1_1Averager.html", null ],
    [ "control_system::Tags::TimescaleTuner< ControlSystem >", "structcontrol__system_1_1Tags_1_1TimescaleTuner.html", null ],
    [ "control_system::Tags::Controller< ControlSystem >", "structcontrol__system_1_1Tags_1_1Controller.html", null ],
    [ "control_system::Tags::ControlError< ControlSystem >", "structcontrol__system_1_1Tags_1_1ControlError.html", null ],
    [ "control_system::Tags::MeasurementsPerUpdate", "structcontrol__system_1_1Tags_1_1MeasurementsPerUpdate.html", null ],
    [ "control_system::Tags::CurrentNumberOfMeasurements", "structcontrol__system_1_1Tags_1_1CurrentNumberOfMeasurements.html", null ],
    [ "control_system::Tags::Verbosity", "structcontrol__system_1_1Tags_1_1Verbosity.html", null ],
    [ "TimescaleTuner", "classTimescaleTuner.html", [
      [ "DecreaseFactor", "structTimescaleTuner_1_1DecreaseFactor.html", null ],
      [ "DecreaseThreshold", "structTimescaleTuner_1_1DecreaseThreshold.html", null ],
      [ "IncreaseFactor", "structTimescaleTuner_1_1IncreaseFactor.html", null ],
      [ "IncreaseThreshold", "structTimescaleTuner_1_1IncreaseThreshold.html", null ],
      [ "InitialTimescales", "structTimescaleTuner_1_1InitialTimescales.html", null ],
      [ "MaxTimescale", "structTimescaleTuner_1_1MaxTimescale.html", null ],
      [ "MinTimescale", "structTimescaleTuner_1_1MinTimescale.html", null ],
      [ "current_timescale", "classTimescaleTuner.html#a089888b2fdc35ba674358dd17efbd48f", null ],
      [ "resize_timescales", "classTimescaleTuner.html#a649f4ab7f12d7fbcb0a55ea3f615f315", null ],
      [ "set_timescale_if_in_allowable_range", "classTimescaleTuner.html#a7e631bc61a2fc9f3df5f8975d17eec26", null ],
      [ "timescales_have_been_set", "classTimescaleTuner.html#af1f334d46c20fa5141fe516aabcd121b", null ],
      [ "update_timescale", "classTimescaleTuner.html#a781efd1162468c8bf7d0bc9537fc8dd6", null ]
    ] ],
    [ "control_system::UpdateFunctionOfTime", "structcontrol__system_1_1UpdateFunctionOfTime.html", null ],
    [ "control_system::ResetFunctionOfTimeExpirationTime", "structcontrol__system_1_1ResetFunctionOfTimeExpirationTime.html", null ],
    [ "domain::FunctionsOfTime::FixedSpeedCubic", "classdomain_1_1FunctionsOfTime_1_1FixedSpeedCubic.html", [
      [ "func", "classdomain_1_1FunctionsOfTime_1_1FixedSpeedCubic.html#a6114d67fdd71efc915ca8d20a78eb1a3", null ],
      [ "func_and_2_derivs", "classdomain_1_1FunctionsOfTime_1_1FixedSpeedCubic.html#a0406338fa4bc79f9913329f1910858c2", null ],
      [ "func_and_deriv", "classdomain_1_1FunctionsOfTime_1_1FixedSpeedCubic.html#a802b157f381439db2d1e3e2fb74a0b14", null ],
      [ "time_bounds", "classdomain_1_1FunctionsOfTime_1_1FixedSpeedCubic.html#a5f28c67fe72f7c9023633d591c2a31b6", null ]
    ] ],
    [ "domain::FunctionsOfTime::SettleToConstant", "classdomain_1_1FunctionsOfTime_1_1SettleToConstant.html", [
      [ "func", "classdomain_1_1FunctionsOfTime_1_1SettleToConstant.html#a954fd93b5952abda365f382fc53212ab", null ],
      [ "func_and_2_derivs", "classdomain_1_1FunctionsOfTime_1_1SettleToConstant.html#ace5d002f10dc4d39a2afa2db58732203", null ],
      [ "func_and_deriv", "classdomain_1_1FunctionsOfTime_1_1SettleToConstant.html#ab79845bb510344e403cc42c654880a72", null ],
      [ "time_bounds", "classdomain_1_1FunctionsOfTime_1_1SettleToConstant.html#a1d94029d8be7a5124e63393364cf1cc2", null ]
    ] ],
    [ "control_system::control_components", "group__ControlSystemGroup.html#ga6ed69fbc3234081d4a0bb84ef176fc62", null ],
    [ "control_system::control_system_events", "group__ControlSystemGroup.html#ga7bbce24937d1c40fb0b87880e9c5d219", null ],
    [ "control_system::control_system_triggers", "group__ControlSystemGroup.html#gaaeb170256e21b2454050158aaf51937c", null ],
    [ "control_system::inputs", "group__ControlSystemGroup.html#ga7b24e33b5fa5b0c5c7e9a05756243d48", null ],
    [ "control_system::calculate_measurement_timescales", "group__ControlSystemGroup.html#ga95a72f35fae0171be6fd523305a635d6", null ],
    [ "control_system::function_of_time_expiration_time", "group__ControlSystemGroup.html#ga5098f75ed02c2d1f0ed6a56cd76e7d9f", null ],
    [ "control_system::initial_expiration_times", "group__ControlSystemGroup.html#ga1cfe2c0a65ba1d01fb8ea46b70a17817", null ],
    [ "control_system::measurement_expiration_time", "group__ControlSystemGroup.html#gadbc0f7b981fe84620ab1668ed6dfd907", null ],
    [ "control_system::write_components_to_disk", "group__ControlSystemGroup.html#ga5d20d917bcfa5c782a87018dd0ee29b6", null ]
];