var group__OptionTagsGroup =
[
    [ "control_system::OptionTags::ControlSystemGroup", "structcontrol__system_1_1OptionTags_1_1ControlSystemGroup.html", null ],
    [ "control_system::OptionTags::ControlSystemInputs< ControlSystem >", "structcontrol__system_1_1OptionTags_1_1ControlSystemInputs.html", null ],
    [ "control_system::OptionTags::WriteDataToDisk", "structcontrol__system_1_1OptionTags_1_1WriteDataToDisk.html", null ],
    [ "control_system::OptionTags::MeasurementsPerUpdate", "structcontrol__system_1_1OptionTags_1_1MeasurementsPerUpdate.html", null ],
    [ "control_system::OptionTags::Verbosity", "structcontrol__system_1_1OptionTags_1_1Verbosity.html", null ],
    [ "domain::OptionTags::DomainCreator< Dim >", "structdomain_1_1OptionTags_1_1DomainCreator.html", null ],
    [ "OptionTags::Limiter< LimiterType >", "structOptionTags_1_1Limiter.html", null ],
    [ "OptionTags::Filter< FilterType >", "structOptionTags_1_1Filter.html", null ],
    [ "OptionTags::VariableFixer< VariableFixerType >", "structOptionTags_1_1VariableFixer.html", null ],
    [ "logging::OptionTags::Verbosity< OptionsGroup >", "structlogging_1_1OptionTags_1_1Verbosity.html", null ],
    [ "OptionTags::NumericalFlux< NumericalFluxType >", "structOptionTags_1_1NumericalFlux.html", null ],
    [ "OptionTags::Strahlkorper< Frame >", "structOptionTags_1_1Strahlkorper.html", null ],
    [ "amr::Criteria::OptionTags::Criteria", "structamr_1_1Criteria_1_1OptionTags_1_1Criteria.html", null ],
    [ "OptionTags::EventsAndTriggers", "structOptionTags_1_1EventsAndTriggers.html", null ],
    [ "OptionTags::AnalyticData< DataType >", "structOptionTags_1_1AnalyticData.html", null ],
    [ "OptionTags::AnalyticSolution< SolutionType >", "structOptionTags_1_1AnalyticSolution.html", null ],
    [ "Tags::AnalyticSolution< SolutionType >", "structTags_1_1AnalyticSolution.html", null ],
    [ "evolution::initial_data::OptionTags::InitialData", "structevolution_1_1initial__data_1_1OptionTags_1_1InitialData.html", null ],
    [ "OptionTags::TimeStepper< StepperType >", "structOptionTags_1_1TimeStepper.html", null ],
    [ "OptionTags::StepChoosers", "structOptionTags_1_1StepChoosers.html", null ],
    [ "OptionTags::InitialTime", "structOptionTags_1_1InitialTime.html", null ],
    [ "OptionTags::InitialTimeStep", "structOptionTags_1_1InitialTimeStep.html", null ],
    [ "OptionTags::InitialSlabSize", "structOptionTags_1_1InitialSlabSize.html", null ]
];