var modules =
[
    [ "Actions", "group__ActionsGroup.html", "group__ActionsGroup" ],
    [ "ADER", "group__AderGroup.html", "group__AderGroup" ],
    [ "Adaptive Mesh Refinement", "group__AmrGroup.html", "group__AmrGroup" ],
    [ "Analytic Data", "group__AnalyticDataGroup.html", "group__AnalyticDataGroup" ],
    [ "Analytic Solutions", "group__AnalyticSolutionsGroup.html", "group__AnalyticSolutionsGroup" ],
    [ "Boundary Conditions", "group__BoundaryConditionsGroup.html", null ],
    [ "Charm++ Extensions", "group__CharmExtensionsGroup.html", "group__CharmExtensionsGroup" ],
    [ "Computational Domain", "group__ComputationalDomainGroup.html", "group__ComputationalDomainGroup" ],
    [ "Conservative System Evolution", "group__ConservativeGroup.html", "group__ConservativeGroup" ],
    [ "Constant Expressions", "group__ConstantExpressionsGroup.html", "group__ConstantExpressionsGroup" ],
    [ "Control System", "group__ControlSystemGroup.html", "group__ControlSystemGroup" ],
    [ "Coordinate Maps", "group__CoordinateMapsGroup.html", "group__CoordinateMapsGroup" ],
    [ "Coordinate Maps, Time-dependent", "group__CoordMapsTimeDependentGroup.html", "group__CoordMapsTimeDependentGroup" ],
    [ "DataBox", "group__DataBoxGroup.html", "group__DataBoxGroup" ],
    [ "DataBox Tags", "group__DataBoxTagsGroup.html", "group__DataBoxTagsGroup" ],
    [ "Data Structures", "group__DataStructuresGroup.html", "group__DataStructuresGroup" ],
    [ "DG-Subcell", "group__DgSubcellGroup.html", "group__DgSubcellGroup" ],
    [ "Discontinuous Galerkin", "group__DiscontinuousGalerkinGroup.html", "group__DiscontinuousGalerkinGroup" ],
    [ "Elliptic Systems", "group__EllipticSystemsGroup.html", "group__EllipticSystemsGroup" ],
    [ "Equations of State", "group__EquationsOfStateGroup.html", "group__EquationsOfStateGroup" ],
    [ "Error Handling", "group__ErrorHandlingGroup.html", "group__ErrorHandlingGroup" ],
    [ "Events and Triggers", "group__EventsAndTriggersGroup.html", "group__EventsAndTriggersGroup" ],
    [ "Evolution Systems", "group__EvolutionSystemsGroup.html", "group__EvolutionSystemsGroup" ],
    [ "Executables", "group__ExecutablesGroup.html", null ],
    [ "File System", "group__FileSystemGroup.html", "group__FileSystemGroup" ],
    [ "Finite Difference", "group__FiniteDifferenceGroup.html", "group__FiniteDifferenceGroup" ],
    [ "General Relativity", "group__GeneralRelativityGroup.html", "group__GeneralRelativityGroup" ],
    [ "HDF5", "group__HDF5Group.html", "group__HDF5Group" ],
    [ "Initialization", "group__InitializationGroup.html", "group__InitializationGroup" ],
    [ "Limiters", "group__LimitersGroup.html", "group__LimitersGroup" ],
    [ "Linear Solver", "group__LinearSolverGroup.html", "group__LinearSolverGroup" ],
    [ "Logging", "group__LoggingGroup.html", "group__LoggingGroup" ],
    [ "Math Functions", "group__MathFunctionsGroup.html", "group__MathFunctionsGroup" ],
    [ "Numerical Algorithms", "group__NumericalAlgorithmsGroup.html", "group__NumericalAlgorithmsGroup" ],
    [ "Numerical Fluxes", "group__NumericalFluxesGroup.html", null ],
    [ "Observers", "group__ObserversGroup.html", "group__ObserversGroup" ],
    [ "Option Groups", "group__OptionGroupsGroup.html", "group__OptionGroupsGroup" ],
    [ "Option Parsing", "group__OptionParsingGroup.html", "group__OptionParsingGroup" ],
    [ "Option Tags", "group__OptionTagsGroup.html", "group__OptionTagsGroup" ],
    [ "Parallelization", "group__ParallelGroup.html", "group__ParallelGroup" ],
    [ "Performance, Efficiency, and Optimizations", "group__PeoGroup.html", "group__PeoGroup" ],
    [ "Pretty Type", "group__PrettyTypeGroup.html", "group__PrettyTypeGroup" ],
    [ "Protocols", "group__ProtocolsGroup.html", "group__ProtocolsGroup" ],
    [ "Python Bindings", "group__PythonBindingsGroup.html", "group__PythonBindingsGroup" ],
    [ "Special Relativity", "group__SpecialRelativityGroup.html", "group__SpecialRelativityGroup" ],
    [ "Spectral", "group__SpectralGroup.html", "group__SpectralGroup" ],
    [ "Spin-weighted spherical harmonics", "group__SwshGroup.html", "group__SwshGroup" ],
    [ "Surfaces", "group__SurfacesGroup.html", "group__SurfacesGroup" ],
    [ "Tensor", "group__TensorGroup.html", "group__TensorGroup" ],
    [ "Tensor Expressions", "group__TensorExpressionsGroup.html", "group__TensorExpressionsGroup" ],
    [ "Testing Framework", "group__TestingFrameworkGroup.html", "group__TestingFrameworkGroup" ],
    [ "Time", "group__TimeGroup.html", "group__TimeGroup" ],
    [ "Time Steppers", "group__TimeSteppersGroup.html", "group__TimeSteppersGroup" ],
    [ "Type Traits", "group__TypeTraitsGroup.html", "group__TypeTraitsGroup" ],
    [ "Utilities", "group__UtilitiesGroup.html", "group__UtilitiesGroup" ],
    [ "Variable Fixing", "group__VariableFixingGroup.html", "group__VariableFixingGroup" ]
];