var searchData=
[
  ['jacobian_0',['Jacobian',['../structdomain_1_1Tags_1_1Jacobian.html',1,'domain::Tags']]],
  ['jacobian_1',['jacobian',['../namespaceStrahlkorperFunctions.html#acadf0536be0d552a94f293a5f73c8a5e',1,'StrahlkorperFunctions::jacobian(const gsl::not_null&lt; StrahlkorperTags::aliases::Jacobian&lt; Fr &gt; * &gt; jac, const tnsr::i&lt; DataVector, 2, ::Frame::Spherical&lt; Fr &gt; &gt; &amp;theta_phi)'],['../namespaceStrahlkorperFunctions.html#a8f54131aa7a7e64187ed8b753075a5e8',1,'StrahlkorperFunctions::jacobian(const tnsr::i&lt; DataVector, 2, ::Frame::Spherical&lt; Fr &gt; &gt; &amp;theta_phi)'],['../structCce_1_1Solutions_1_1SphericalMetricData.html#ab263cb5d0eba20dd88b19c8f02c228f6',1,'Cce::Solutions::SphericalMetricData::jacobian()'],['../classdomain_1_1CoordinateMap.html#ad8af9b6b3c44924947d8699df6bf0996',1,'domain::CoordinateMap::jacobian(tnsr::I&lt; DataVector, dim, SourceFrame &gt; source_point, const double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt; &gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt; &gt;{}) const override'],['../classdomain_1_1CoordinateMap.html#ac3e6a9510217b0f79359a5bba343a3c7',1,'domain::CoordinateMap::jacobian(tnsr::I&lt; double, dim, SourceFrame &gt; source_point, const double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt; &gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt; &gt;{}) const override'],['../classdomain_1_1CoordinateMapBase.html#a309a8994fa14c7acdc211fbe2caf0729',1,'domain::CoordinateMapBase::jacobian(tnsr::I&lt; DataVector, Dim, SourceFrame &gt; source_point, double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt; &gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt; &gt;{}) const =0'],['../classdomain_1_1CoordinateMapBase.html#af34e14d9d34ee5893f68b75f32b35237',1,'domain::CoordinateMapBase::jacobian(tnsr::I&lt; double, Dim, SourceFrame &gt; source_point, double time=std::numeric_limits&lt; double &gt;::signaling_NaN(), const std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt; &gt; &amp;functions_of_time=std::unordered_map&lt; std::string, std::unique_ptr&lt; domain::FunctionsOfTime::FunctionOfTime &gt; &gt;{}) const =0']]],
  ['jacobian_2',['Jacobian',['../structStrahlkorperTags_1_1Jacobian.html',1,'StrahlkorperTags']]],
  ['jacobian_5fdiagnostic_3',['jacobian_diagnostic',['../group__ComputationalDomainGroup.html#ga22ab91fc5d9d14fca8a1034e69832bf6',1,'domain::jacobian_diagnostic(const ::Jacobian&lt; DataVector, Dim, Frame::ElementLogical, Fr &gt; &amp;analytic_jacobian, const tnsr::I&lt; DataVector, Dim, Fr &gt; &amp;mapped_coords, const ::Mesh&lt; Dim &gt; &amp;mesh)'],['../group__ComputationalDomainGroup.html#gab579049797d1e22b31d7e21288c53370',1,'domain::jacobian_diagnostic(const gsl::not_null&lt; tnsr::i&lt; DataVector, Dim, Frame::ElementLogical &gt; * &gt; jacobian_diag, const ::Jacobian&lt; DataVector, Dim, Frame::ElementLogical, Fr &gt; &amp;analytic_jacobian, const tnsr::I&lt; DataVector, Dim, Fr &gt; &amp;mapped_coords, const ::Mesh&lt; Dim &gt; &amp;mesh)'],['../group__ComputationalDomainGroup.html#ga45b5650adddebf194bd3d70113a73eb6',1,'domain::jacobian_diagnostic(const gsl::not_null&lt; tnsr::i&lt; DataVector, Dim, typename Frame::ElementLogical &gt; * &gt; jacobian_diag, const Jacobian&lt; DataVector, Dim, typename Frame::ElementLogical, Fr &gt; &amp;analytic_jacobian, const TensorMetafunctions::prepend_spatial_index&lt; tnsr::I&lt; DataVector, Dim, Fr &gt;, Dim, UpLo::Lo, typename Frame::ElementLogical &gt; &amp;numeric_jacobian_transpose)']]],
  ['jacobian_5fis_5ftime_5fdependent_4',['jacobian_is_time_dependent',['../classdomain_1_1CoordinateMapBase.html#a1f563b98494fef9d59091b3163c0e8b5',1,'domain::CoordinateMapBase::jacobian_is_time_dependent()'],['../classdomain_1_1CoordinateMap.html#a41a47903acc9a762d03d0647d3475372',1,'domain::CoordinateMap::jacobian_is_time_dependent()']]],
  ['jacobiancompute_5',['JacobianCompute',['../structdomain_1_1Tags_1_1JacobianCompute.html',1,'domain::Tags::JacobianCompute&lt; Dim, SourceFrame, TargetFrame &gt;'],['../structStrahlkorperTags_1_1JacobianCompute.html',1,'StrahlkorperTags::JacobianCompute&lt; Frame &gt;']]],
  ['jacobiandiagnostic_6',['JacobianDiagnostic',['../structdomain_1_1Tags_1_1JacobianDiagnostic.html',1,'domain::Tags']]],
  ['jacobiandiagnosticcompute_7',['JacobianDiagnosticCompute',['../structdomain_1_1Tags_1_1JacobianDiagnosticCompute.html',1,'domain::Tags']]],
  ['jacobipreconditioner_8',['JacobiPreconditioner',['../structTestHelpers_1_1LinearSolver_1_1JacobiPreconditioner.html',1,'TestHelpers::LinearSolver']]],
  ['jbarqminus2ethbeta_9',['JbarQMinus2EthBeta',['../structCce_1_1Tags_1_1JbarQMinus2EthBeta.html',1,'Cce::Tags']]],
  ['jetdensity_10',['JetDensity',['../structgrmhd_1_1AnalyticData_1_1SlabJet_1_1JetDensity.html',1,'grmhd::AnalyticData::SlabJet']]],
  ['jetelectronfraction_11',['JetElectronFraction',['../structgrmhd_1_1AnalyticData_1_1SlabJet_1_1JetElectronFraction.html',1,'grmhd::AnalyticData::SlabJet']]],
  ['jetpressure_12',['JetPressure',['../structgrmhd_1_1AnalyticData_1_1SlabJet_1_1JetPressure.html',1,'grmhd::AnalyticData::SlabJet']]],
  ['jetvelocity_13',['JetVelocity',['../structgrmhd_1_1AnalyticData_1_1SlabJet_1_1JetVelocity.html',1,'grmhd::AnalyticData::SlabJet']]],
  ['jmp_5fbuf_14',['jmp_buf',['http://en.cppreference.com/w/cpp/utility/program/jmp_buf.html',1,'std']]],
  ['join_15',['join',['http://en.cppreference.com/w/cpp/thread/thread/join.html',1,'std::thread']]],
  ['join_16',['Join',['../group__AmrGroup.html#gga6874579f1400ff7d0d77cbfa978289e2aa286d9991c6a547ae25a5f5216164b8f',1,'amr']]],
  ['joinable_17',['joinable',['http://en.cppreference.com/w/cpp/thread/thread/joinable.html',1,'std::thread']]],
  ['jumpposition_18',['JumpPosition',['../structNewtonianEuler_1_1AnalyticData_1_1ShuOsherTube_1_1JumpPosition.html',1,'NewtonianEuler::AnalyticData::ShuOsherTube']]]
];
