var searchData=
[
  ['n_0',['N',['../structelliptic_1_1Triggers_1_1EveryNIterations_1_1N.html',1,'elliptic::Triggers::EveryNIterations']]],
  ['name_1',['Name',['../structEvents_1_1ObserveAtExtremum_3_01ObservationValueTag_00_01tmpl_1_1list_3_01ObservableTensor3b70b81d22e2259317cb18a0d451ef82.html',1,'Events::ObserveAtExtremum&lt; ObservationValueTag, tmpl::list&lt; ObservableTensorTags... &gt;, tmpl::list&lt; NonTensorComputeTags... &gt;, ArraySectionIdTag &gt;::ObserveTensors::Name'],['../structEvents_1_1ObserveNorms_3_01ObservationValueTag_00_01tmpl_1_1list_3_01ObservableTensorTags_a09056eecd77fc9bbf5ffb943b2fc0a3.html',1,'Events::ObserveNorms&lt; ObservationValueTag, tmpl::list&lt; ObservableTensorTags... &gt;, tmpl::list&lt; NonTensorComputeTags... &gt;, ArraySectionIdTag &gt;::ObserveTensor::Name']]],
  ['nano_2',['nano',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['nanoseconds_3',['nanoseconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['neartimes_4',['NearTimes',['../classTriggers_1_1NearTimes.html',1,'Triggers']]],
  ['negate_5',['Negate',['../structfuncl_1_1Negate.html',1,'funcl']]],
  ['negate_6',['negate',['http://en.cppreference.com/w/cpp/utility/functional/negate.html',1,'std']]],
  ['negate_7',['Negate',['../structtenex_1_1Negate.html',1,'tenex']]],
  ['negation_8',['negation',['http://en.cppreference.com/w/cpp/types/negation.html',1,'std']]],
  ['negation_3c_20std_3a_3ais_5fsame_3c_20get_5fbinop_5fdatatype_5fimpl_3c_20upcast_5fif_5fderived_5fvector_5ftype_3c_20tensorexpressiontype_3a_3atype_20_3e_3a_3atype_2c_20upcast_5fif_5fderived_5fvector_5ftype_3c_20numbertype_20_3e_3a_3atype_20_3e_3a_3atype_2c_20nosuchtype_20_3e_20_3e_9',['negation&lt; std::is_same&lt; get_binop_datatype_impl&lt; upcast_if_derived_vector_type&lt; TensorExpressionType::type &gt;::type, upcast_if_derived_vector_type&lt; NumberType &gt;::type &gt;::type, NoSuchType &gt; &gt;',['http://en.cppreference.com/w/cpp/types/negation.html',1,'std']]],
  ['negation_3c_20std_3a_3ais_5fsame_3c_20get_5fbinop_5fdatatype_5fimpl_3c_20upcast_5fif_5fderived_5fvector_5ftype_3c_20x1_20_3e_3a_3atype_2c_20upcast_5fif_5fderived_5fvector_5ftype_3c_20x2_20_3e_3a_3atype_20_3e_3a_3atype_2c_20nosuchtype_20_3e_20_3e_10',['negation&lt; std::is_same&lt; get_binop_datatype_impl&lt; upcast_if_derived_vector_type&lt; X1 &gt;::type, upcast_if_derived_vector_type&lt; X2 &gt;::type &gt;::type, NoSuchType &gt; &gt;',['http://en.cppreference.com/w/cpp/types/negation.html',1,'std']]],
  ['negative_5fbinomial_5fdistribution_11',['negative_binomial_distribution',['http://en.cppreference.com/w/cpp/numeric/random/negative_binomial_distribution.html',1,'std']]],
  ['negativeexpansion_12',['NegativeExpansion',['../structXcts_1_1BoundaryConditions_1_1ApparentHorizon_1_1NegativeExpansion.html',1,'Xcts::BoundaryConditions::ApparentHorizon']]],
  ['neighborflags_13',['NeighborFlags',['../structamr_1_1Tags_1_1NeighborFlags.html',1,'amr::Tags']]],
  ['neighbormesh_14',['NeighborMesh',['../structevolution_1_1dg_1_1Tags_1_1NeighborMesh.html',1,'evolution::dg::Tags']]],
  ['neighbormortars_15',['NeighborMortars',['../structelliptic_1_1dg_1_1subdomain__operator_1_1Tags_1_1NeighborMortars.html',1,'elliptic::dg::subdomain_operator::Tags']]],
  ['neighborpackageddata_16',['NeighborPackagedData',['../structBurgers_1_1subcell_1_1NeighborPackagedData.html',1,'Burgers::subcell::NeighborPackagedData'],['../structgrmhd_1_1GhValenciaDivClean_1_1subcell_1_1NeighborPackagedData.html',1,'grmhd::GhValenciaDivClean::subcell::NeighborPackagedData'],['../structgrmhd_1_1ValenciaDivClean_1_1subcell_1_1NeighborPackagedData.html',1,'grmhd::ValenciaDivClean::subcell::NeighborPackagedData'],['../structNewtonianEuler_1_1subcell_1_1NeighborPackagedData.html',1,'NewtonianEuler::subcell::NeighborPackagedData'],['../structScalarAdvection_1_1subcell_1_1NeighborPackagedData.html',1,'ScalarAdvection::subcell::NeighborPackagedData']]],
  ['neighbors_17',['Neighbors',['../classNeighbors.html',1,'']]],
  ['neighbortcidecisions_18',['NeighborTciDecisions',['../structevolution_1_1dg_1_1subcell_1_1Tags_1_1NeighborTciDecisions.html',1,'evolution::dg::subcell::Tags']]],
  ['neighborweight_19',['NeighborWeight',['../structLimiters_1_1Weno_3_01VolumeDim_00_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4_1_1NeighborWeight.html',1,'Limiters::Weno&lt; VolumeDim, tmpl::list&lt; Tags... &gt; &gt;']]],
  ['nested_5fexception_20',['nested_exception',['http://en.cppreference.com/w/cpp/error/nested_exception.html',1,'std']]],
  ['neumannweight_21',['NeumannWeight',['../structPoisson_1_1BoundaryConditions_1_1Robin_1_1NeumannWeight.html',1,'Poisson::BoundaryConditions::Robin']]],
  ['neutronstarcenter_22',['NeutronStarCenter',['../structcontrol__system_1_1measurements_1_1Tags_1_1NeutronStarCenter.html',1,'control_system::measurements::Tags']]],
  ['new_5fdelete_5fresource_23',['new_delete_resource',['http://en.cppreference.com/w/cpp/experimental/new_delete_resource.html',1,'std::experimental::pmr']]],
  ['new_5fhandler_24',['new_handler',['http://en.cppreference.com/w/cpp/memory/new/new_handler.html',1,'std']]],
  ['newmanhamlin_25',['NewmanHamlin',['../classgrmhd_1_1ValenciaDivClean_1_1PrimitiveRecoverySchemes_1_1NewmanHamlin.html',1,'grmhd::ValenciaDivClean::PrimitiveRecoverySchemes']]],
  ['news_26',['News',['../structCce_1_1Tags_1_1News.html',1,'Cce::Tags']]],
  ['newtonraphson_27',['NewtonRaphson',['../structNonlinearSolver_1_1newton__raphson_1_1NewtonRaphson.html',1,'NonlinearSolver::newton_raphson']]],
  ['newtonraphsongroup_28',['NewtonRaphsonGroup',['../structelliptic_1_1nonlinear__solver_1_1OptionTags_1_1NewtonRaphsonGroup.html',1,'elliptic::nonlinear_solver::OptionTags']]],
  ['next_29',['Next',['../structTags_1_1Next.html',1,'Tags']]],
  ['nextcheck_30',['NextCheck',['../structTestHelpers_1_1DenseTriggers_1_1BoxTrigger_1_1NextCheck.html',1,'TestHelpers::DenseTriggers::BoxTrigger&lt; Label &gt;::NextCheck'],['../structTestHelpers_1_1DenseTriggers_1_1TestTrigger_1_1NextCheck.html',1,'TestHelpers::DenseTriggers::TestTrigger::NextCheck']]],
  ['nodegroup_31',['Nodegroup',['../structParallel_1_1Algorithms_1_1Nodegroup.html',1,'Parallel::Algorithms']]],
  ['nodeid_32',['NodeId',['../structActionTesting_1_1NodeId.html',1,'ActionTesting']]],
  ['nodelock_33',['NodeLock',['../classParallel_1_1NodeLock.html',1,'Parallel']]],
  ['noderivative_34',['NoDerivative',['../structSpectral_1_1Swsh_1_1Tags_1_1NoDerivative.html',1,'Spectral::Swsh::Tags']]],
  ['nodesexpectedtocontributereductions_35',['NodesExpectedToContributeReductions',['../structobservers_1_1Tags_1_1NodesExpectedToContributeReductions.html',1,'observers::Tags']]],
  ['nodesthatcontributedreductions_36',['NodesThatContributedReductions',['../structobservers_1_1Tags_1_1NodesThatContributedReductions.html',1,'observers::Tags']]],
  ['noendtime_37',['NoEndTime',['../structCce_1_1Tags_1_1NoEndTime.html',1,'Cce::Tags']]],
  ['noformatter_38',['NoFormatter',['../structobservers_1_1NoFormatter.html',1,'observers']]],
  ['noframe_39',['NoFrame',['../structFrame_1_1NoFrame.html',1,'Frame']]],
  ['noincomingradiation_40',['NoIncomingRadiation',['../structCce_1_1InitializeJ_1_1NoIncomingRadiation.html',1,'Cce::InitializeJ']]],
  ['noiterationcallback_41',['NoIterationCallback',['../structLinearSolver_1_1Serial_1_1NoIterationCallback.html',1,'LinearSolver::Serial']]],
  ['nonconservativesystem_42',['NonconservativeSystem',['../structInitialization_1_1Actions_1_1NonconservativeSystem.html',1,'Initialization::Actions']]],
  ['noncopyable_43',['NonCopyable',['../structNonCopyable.html',1,'']]],
  ['none_44',['None',['../structdomain_1_1BoundaryConditions_1_1None.html',1,'domain::BoundaryConditions::None&lt; SystemBoundaryConditionBaseClass &gt;'],['../classdomain_1_1creators_1_1time__dependence_1_1None.html',1,'domain::creators::time_dependence::None&lt; MeshDim &gt;'],['../structOptions_1_1AutoLabel_1_1None.html',1,'Options::AutoLabel::None']]],
  ['nonesuch_45',['nonesuch',['http://en.cppreference.com/w/cpp/experimental/nonesuch.html',1,'std::experimental']]],
  ['noneuclideanmagnitude_46',['NonEuclideanMagnitude',['../structTags_1_1NonEuclideanMagnitude.html',1,'Tags']]],
  ['nonlinearsolvergroup_47',['NonlinearSolverGroup',['../structelliptic_1_1nonlinear__solver_1_1OptionTags_1_1NonlinearSolverGroup.html',1,'elliptic::nonlinear_solver::OptionTags']]],
  ['nonlinearweightexponent_48',['NonlinearWeightExponent',['../structgrmhd_1_1ValenciaDivClean_1_1fd_1_1Wcns5zPrim_1_1NonlinearWeightExponent.html',1,'grmhd::ValenciaDivClean::fd::Wcns5zPrim::NonlinearWeightExponent'],['../structNewtonianEuler_1_1fd_1_1AoWeno53Prim_1_1NonlinearWeightExponent.html',1,'NewtonianEuler::fd::AoWeno53Prim&lt; Dim &gt;::NonlinearWeightExponent'],['../structScalarAdvection_1_1fd_1_1AoWeno53_1_1NonlinearWeightExponent.html',1,'ScalarAdvection::fd::AoWeno53&lt; Dim &gt;::NonlinearWeightExponent']]],
  ['nopreconditioner_49',['NoPreconditioner',['../structLinearSolver_1_1Serial_1_1NoPreconditioner.html',1,'LinearSolver::Serial']]],
  ['normal_5fdistribution_50',['normal_distribution',['http://en.cppreference.com/w/cpp/numeric/random/normal_distribution.html',1,'std']]],
  ['normalcovector_51',['NormalCovector',['../structevolution_1_1dg_1_1Tags_1_1NormalCovector.html',1,'evolution::dg::Tags']]],
  ['normalcovectorandmagnitude_52',['NormalCovectorAndMagnitude',['../structevolution_1_1dg_1_1Tags_1_1NormalCovectorAndMagnitude.html',1,'evolution::dg::Tags']]],
  ['normaldotflux_53',['NormalDotFlux',['../structTags_1_1NormalDotFlux.html',1,'Tags']]],
  ['normaldotfluxcompute_54',['NormalDotFluxCompute',['../structTags_1_1NormalDotFluxCompute.html',1,'Tags']]],
  ['normaldotfluxforjump_55',['NormalDotFluxForJump',['../structelliptic_1_1dg_1_1Tags_1_1NormalDotFluxForJump.html',1,'elliptic::dg::Tags']]],
  ['normaldotnumericalflux_56',['NormalDotNumericalFlux',['../structTags_1_1NormalDotNumericalFlux.html',1,'Tags']]],
  ['normaldotoneindexconstraint_57',['NormalDotOneIndexConstraint',['../structgh_1_1Tags_1_1NormalDotOneIndexConstraint.html',1,'gh::Tags']]],
  ['normalized_58',['Normalized',['../structTags_1_1Normalized.html',1,'Tags']]],
  ['normalizedcompute_59',['NormalizedCompute',['../structTags_1_1NormalizedCompute.html',1,'Tags']]],
  ['normaloneform_60',['NormalOneForm',['../structStrahlkorperTags_1_1NormalOneForm.html',1,'StrahlkorperTags']]],
  ['normaloneformcompute_61',['NormalOneFormCompute',['../structStrahlkorperTags_1_1NormalOneFormCompute.html',1,'StrahlkorperTags']]],
  ['normtype_62',['NormType',['../structEvents_1_1ObserveNorms_3_01ObservationValueTag_00_01tmpl_1_1list_3_01ObservableTensorTags_4db82ab17f0a9d5a310573f224a2f092.html',1,'Events::ObserveNorms&lt; ObservationValueTag, tmpl::list&lt; ObservableTensorTags... &gt;, tmpl::list&lt; NonTensorComputeTags... &gt;, ArraySectionIdTag &gt;::ObserveTensor']]],
  ['nosection_63',['NoSection',['../structParallel_1_1NoSection.html',1,'Parallel']]],
  ['nosource_64',['NoSource',['../structNewtonianEuler_1_1Sources_1_1NoSource.html',1,'NewtonianEuler::Sources']]],
  ['nosuchtype_65',['NoSuchType',['../structNoSuchType.html',1,'']]],
  ['not_66',['Not',['../classTriggers_1_1Not.html',1,'Triggers']]],
  ['not_5fequal_5fto_67',['not_equal_to',['http://en.cppreference.com/w/cpp/utility/functional/not_equal_to.html',1,'std']]],
  ['not_5fnull_68',['not_null',['../classgsl_1_1not__null.html',1,'gsl']]],
  ['not_5fnull_3c_20const_20timesteppers_3a_3aboundaryhistory_20_2a_20_3e_69',['not_null&lt; const TimeSteppers::BoundaryHistory * &gt;',['../classgsl_1_1not__null.html',1,'gsl']]],
  ['not_5fnull_3c_20datavector_20_2a_20_3e_70',['not_null&lt; DataVector * &gt;',['../classgsl_1_1not__null.html',1,'gsl']]],
  ['not_5fnull_3c_20db_3a_3adatabox_3c_20dbtags_20_3e_20_2a_20_3e_71',['not_null&lt; db::DataBox&lt; DbTags &gt; * &gt;',['../classgsl_1_1not__null.html',1,'gsl']]],
  ['not_5fnull_3c_20std_3a_3aarray_3c_20gsl_3a_3aspan_3c_20double_20_3e_2c_20dim_20_3e_20_2a_20_3e_72',['not_null&lt; std::array&lt; gsl::span&lt; double &gt;, dim &gt; * &gt;',['../classgsl_1_1not__null.html',1,'gsl']]],
  ['not_5fnull_3c_20timesteppers_3a_3aboundaryhistory_20_2a_20_3e_73',['not_null&lt; TimeSteppers::BoundaryHistory * &gt;',['../classgsl_1_1not__null.html',1,'gsl']]],
  ['nothrow_5ft_74',['nothrow_t',['http://en.cppreference.com/w/cpp/memory/new/nothrow_t.html',1,'std']]],
  ['notready_75',['NotReady',['../structTestHelpers_1_1DenseTriggers_1_1TestTrigger_1_1NotReady.html',1,'TestHelpers::DenseTriggers::TestTrigger']]],
  ['novalue_76',['NoValue',['../structTimeSteppers_1_1History_1_1NoValue.html',1,'TimeSteppers::History']]],
  ['null_5fmemory_5fresource_77',['null_memory_resource',['http://en.cppreference.com/w/cpp/experimental/null_Memory_resource.html',1,'std::experimental::pmr']]],
  ['nullopt_5ft_78',['nullopt_t',['http://en.cppreference.com/w/cpp/utility/optional/nullopt_t.html',1,'std']]],
  ['nullptr_5ft_79',['nullptr_t',['http://en.cppreference.com/w/cpp/types/nullptr_t.html',1,'std']]],
  ['num_5fget_80',['num_get',['http://en.cppreference.com/w/cpp/locale/num_get.html',1,'std']]],
  ['num_5fput_81',['num_put',['http://en.cppreference.com/w/cpp/locale/num_put.html',1,'std']]],
  ['numberasexpression_82',['NumberAsExpression',['../structtenex_1_1NumberAsExpression.html',1,'tenex']]],
  ['numberofelements_83',['NumberOfElements',['../structintrp_1_1Tags_1_1NumberOfElements.html',1,'intrp::Tags']]],
  ['numberofpoints_84',['NumberOfPoints',['../structintrp_1_1OptionHolders_1_1LineSegment_1_1NumberOfPoints.html',1,'intrp::OptionHolders::LineSegment&lt; VolumeDim &gt;::NumberOfPoints'],['../structMakeWithValueImpls_1_1NumberOfPoints.html',1,'MakeWithValueImpls::NumberOfPoints&lt; T, typename &gt;']]],
  ['numberofpoints_3c_20blaze_3a_3adynamicvector_3c_20t_2c_20tf_2c_20tag_20_3e_20_3e_85',['NumberOfPoints&lt; blaze::DynamicVector&lt; T, TF, Tag &gt; &gt;',['../structMakeWithValueImpls_1_1NumberOfPoints_3_01blaze_1_1DynamicVector_3_01T_00_01TF_00_01Tag_01_4_01_4.html',1,'MakeWithValueImpls']]],
  ['numberofpoints_3c_20blaze_3a_3astaticvector_3c_20t_2c_20n_2c_20tf_2c_20af_2c_20pf_2c_20tag_20_3e_20_3e_86',['NumberOfPoints&lt; blaze::StaticVector&lt; T, N, TF, AF, PF, Tag &gt; &gt;',['../structMakeWithValueImpls_1_1NumberOfPoints_3_01blaze_1_1StaticVector_3_01T_00_01N_00_01TF_00_01AF_00_01PF_00_01Tag_01_4_01_4.html',1,'MakeWithValueImpls']]],
  ['numberofpoints_3c_20size_5ft_20_3e_87',['NumberOfPoints&lt; size_t &gt;',['../structMakeWithValueImpls_1_1NumberOfPoints_3_01size__t_01_4.html',1,'MakeWithValueImpls']]],
  ['numberofpoints_3c_20spinweighted_3c_20spinweightedtype_2c_20spin_20_3e_20_3e_88',['NumberOfPoints&lt; SpinWeighted&lt; SpinWeightedType, Spin &gt; &gt;',['../structMakeWithValueImpls_1_1NumberOfPoints_3_01SpinWeighted_3_01SpinWeightedType_00_01Spin_01_4_01_4.html',1,'MakeWithValueImpls']]],
  ['numberofpoints_3c_20tensor_3c_20t_2c_20structure_2e_2e_2e_20_3e_20_3e_89',['NumberOfPoints&lt; Tensor&lt; T, Structure... &gt; &gt;',['../structMakeWithValueImpls_1_1NumberOfPoints_3_01Tensor_3_01T_00_01Structure_8_8_8_01_4_01_4.html',1,'MakeWithValueImpls']]],
  ['numberofpoints_3c_20variables_3c_20taglist_20_3e_20_3e_90',['NumberOfPoints&lt; Variables&lt; TagList &gt; &gt;',['../structMakeWithValueImpls_1_1NumberOfPoints_3_01Variables_3_01TagList_01_4_01_4.html',1,'MakeWithValueImpls']]],
  ['numberofradialpoints_91',['NumberOfRadialPoints',['../structCce_1_1OptionTags_1_1NumberOfRadialPoints.html',1,'Cce::OptionTags::NumberOfRadialPoints'],['../structCce_1_1Tags_1_1NumberOfRadialPoints.html',1,'Cce::Tags::NumberOfRadialPoints'],['../structSpectral_1_1Swsh_1_1Tags_1_1NumberOfRadialPoints.html',1,'Spectral::Swsh::Tags::NumberOfRadialPoints']]],
  ['numberofradialpointsbase_92',['NumberOfRadialPointsBase',['../structSpectral_1_1Swsh_1_1Tags_1_1NumberOfRadialPointsBase.html',1,'Spectral::Swsh::Tags']]],
  ['numberphipoints_93',['NumberPhiPoints',['../structintrp_1_1OptionHolders_1_1WedgeSectionTorus_1_1NumberPhiPoints.html',1,'intrp::OptionHolders::WedgeSectionTorus']]],
  ['numberradialpoints_94',['NumberRadialPoints',['../structintrp_1_1OptionHolders_1_1WedgeSectionTorus_1_1NumberRadialPoints.html',1,'intrp::OptionHolders::WedgeSectionTorus']]],
  ['numberthetapoints_95',['NumberThetaPoints',['../structintrp_1_1OptionHolders_1_1WedgeSectionTorus_1_1NumberThetaPoints.html',1,'intrp::OptionHolders::WedgeSectionTorus']]],
  ['numeric_5flimits_96',['numeric_limits',['http://en.cppreference.com/w/cpp/types/numeric_limits.html',1,'std']]],
  ['numericalflux_97',['NumericalFlux',['../structOptionTags_1_1NumericalFlux.html',1,'OptionTags::NumericalFlux&lt; NumericalFluxType &gt;'],['../structTags_1_1NumericalFlux.html',1,'Tags::NumericalFlux&lt; NumericalFluxType &gt;']]],
  ['numericalfluxgroup_98',['NumericalFluxGroup',['../structOptionTags_1_1NumericalFluxGroup.html',1,'OptionTags']]],
  ['numericinitialdata_99',['NumericInitialData',['../structevolution_1_1NumericInitialData.html',1,'evolution::NumericInitialData'],['../structevolution_1_1protocols_1_1NumericInitialData.html',1,'evolution::protocols::NumericInitialData'],['../classgh_1_1NumericInitialData.html',1,'gh::NumericInitialData'],['../classgrmhd_1_1GhValenciaDivClean_1_1NumericInitialData.html',1,'grmhd::GhValenciaDivClean::NumericInitialData'],['../classgrmhd_1_1ValenciaDivClean_1_1NumericInitialData.html',1,'grmhd::ValenciaDivClean::NumericInitialData']]],
  ['numpunct_100',['numpunct',['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'std']]],
  ['numpunct_5fbyname_101',['numpunct_byname',['http://en.cppreference.com/w/cpp/locale/numpunct_byname.html',1,'std']]]
];
