var searchData=
[
  ['k_0',['k',['http://en.cppreference.com/w/cpp/numeric/random/negative_binomial_distribution/params.html',1,'std::negative_binomial_distribution']]],
  ['kappa_5ftimes_5fp_5fover_5frho_5fsquared_5ffrom_5fdensity_1',['kappa_times_p_over_rho_squared_from_density',['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_011_01_4.html#a98964d99c7a326f0df05028ff533e44d',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 1 &gt;::kappa_times_p_over_rho_squared_from_density(const Scalar&lt; double &gt; &amp;) const =0'],['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_011_01_4.html#ad75cb6d784ef0c2a31d4b639597e969a',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 1 &gt;::kappa_times_p_over_rho_squared_from_density(const Scalar&lt; DataVector &gt; &amp;) const =0']]],
  ['kappa_5ftimes_5fp_5fover_5frho_5fsquared_5ffrom_5fdensity_5fand_5fenergy_2',['kappa_times_p_over_rho_squared_from_density_and_energy',['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_012_01_4.html#abcb7b2feb5bfba9d794d33c19a83bf8c',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 2 &gt;::kappa_times_p_over_rho_squared_from_density_and_energy(const Scalar&lt; double &gt; &amp;, const Scalar&lt; double &gt; &amp;) const =0'],['../classEquationsOfState_1_1EquationOfState_3_01IsRelativistic_00_012_01_4.html#a959ad41f224129aa4cf0e78316f8ff7e',1,'EquationsOfState::EquationOfState&lt; IsRelativistic, 2 &gt;::kappa_times_p_over_rho_squared_from_density_and_energy(const Scalar&lt; DataVector &gt; &amp;, const Scalar&lt; DataVector &gt; &amp;) const =0']]],
  ['kerr_5fhorizon_5fradius_3',['kerr_horizon_radius',['../namespacegr_1_1Solutions.html#a2dd912db52962a75f772ef5fd4db347f',1,'gr::Solutions']]],
  ['kerr_5fschild_5fradius_5ffrom_5fboyer_5flindquist_4',['kerr_schild_radius_from_boyer_lindquist',['../namespacegr_1_1Solutions.html#ac5ac9d3613d21bc97ffdb522f0f1f836',1,'gr::Solutions']]],
  ['kerrhorizonconforming_5',['KerrHorizonConforming',['../classdomain_1_1CoordinateMaps_1_1KerrHorizonConforming.html#a6b9508afc9ec7c410221d1aa905fb1a7',1,'domain::CoordinateMaps::KerrHorizonConforming']]],
  ['key_5fcomp_6',['key_comp',['http://en.cppreference.com/w/cpp/container/multimap/key_comp.html',1,'std::pmr::multimap::key_comp()'],['http://en.cppreference.com/w/cpp/container/set/key_comp.html',1,'std::set::key_comp()'],['http://en.cppreference.com/w/cpp/container/set/key_comp.html',1,'std::pmr::set::key_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/key_comp.html',1,'std::pmr::multiset::key_comp()'],['http://en.cppreference.com/w/cpp/container/map/key_comp.html',1,'std::pmr::map::key_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/key_comp.html',1,'std::multiset::key_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/key_comp.html',1,'std::multimap::key_comp()'],['http://en.cppreference.com/w/cpp/container/map/key_comp.html',1,'std::map::key_comp()']]],
  ['key_5feq_7',['key_eq',['http://en.cppreference.com/w/cpp/container/unordered_multiset/key_eq.html',1,'std::pmr::unordered_multiset::key_eq()'],['../classFixedHashMap.html#a46aa5223b63c24007e1c2c040fa8eec5',1,'FixedHashMap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_set/key_eq.html',1,'std::unordered_set::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multiset/key_eq.html',1,'std::unordered_multiset::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/key_eq.html',1,'std::unordered_multimap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_map/key_eq.html',1,'std::unordered_map::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_set/key_eq.html',1,'std::pmr::unordered_set::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_multimap/key_eq.html',1,'std::pmr::unordered_multimap::key_eq()'],['http://en.cppreference.com/w/cpp/container/unordered_map/key_eq.html',1,'std::pmr::unordered_map::key_eq()']]],
  ['keys_5fof_8',['keys_of',['../group__UtilitiesGroup.html#ga495b431a620b10beb24f1afc90b77e20',1,'keys_of(const std::unordered_map&lt; K, V, H &gt; &amp;m):&#160;StdHelpers.hpp'],['../group__UtilitiesGroup.html#gaf707b57628e9425c91d92eb278a52c99',1,'keys_of(const std::map&lt; K, V, C &gt; &amp;m):&#160;StdHelpers.hpp']]],
  ['kinetic_5fenergy_5fdensity_9',['kinetic_energy_density',['../namespaceNewtonianEuler.html#a2a300ab3d9d1299528517a23e1479402',1,'NewtonianEuler::kinetic_energy_density(gsl::not_null&lt; Scalar&lt; DataType &gt; * &gt; result, const Scalar&lt; DataType &gt; &amp;mass_density, const tnsr::I&lt; DataType, Dim, Fr &gt; &amp;velocity)'],['../namespaceNewtonianEuler.html#a2b4389582d1ebb8590e32028dacc5f02',1,'NewtonianEuler::kinetic_energy_density(const Scalar&lt; DataType &gt; &amp;mass_density, const tnsr::I&lt; DataType, Dim, Fr &gt; &amp;velocity)']]],
  ['knuth_5fb_10',['knuth_b',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine/shuffle_order_engine.html',1,'std::knuth_b']]],
  ['kreiss_5foliger_5ffilter_11',['kreiss_oliger_filter',['../namespacefd.html#a8cd8fc8b73d4f1ab74d2d285312353ea',1,'fd']]],
  ['kxrcf_5findicator_12',['kxrcf_indicator',['../group__LimitersGroup.html#gacc63540b10e171f9a5bc77215cf3a724',1,'NewtonianEuler::Limiters::Tci']]]
];
